---
title: "R Notebook"
output: html_notebook
author: "Jessica Teixeira Araujo"
---

Step-by-step for performing the Chi-Square Test

Step 1: Assuming a significance level of 5%, i.e., α = 0.05.
```{r}
alfa <- 0.05
print(alfa)
```
Step 2: Considering a confidence level of 95%.

```{r}
confidence_level <- (1 - alfa) * 100
print(confidence_level)
```
Step 3: Constructing vectors containing the experimental data.

```{r}
fo <- c(6,8,11,7,8)
print(fo)
fe <- c(6.8,8.3,8.9,7.1,8.8)
print(fe)
```
Step 4: Applying the function needed to perform the test → chisq.test

```{r}
chisq.test(fo,p=fe, rescale.p=TRUE)
```
Step 5: Extracting the p-value for decision making using code.

```{r}
p_value <- chisq.test(fo,p=fe, rescale.p=TRUE)$p.value
print(p_value)
```
Step 6: Making the decision.

```{r}
if (p_value > alfa) {
  cat("Since the p-value is greater than α =",alfa,", there is not enough evidence to reject Ho at the",confidence_level,"% confidence level.")
} else {
  cat("Since the p-value is less than α =",alfa,", there is enough evidence to reject Ho at the",confidence_level,"% confidence level.")
}
```


